
data = <<__eof__
 [
{'S', 'R', "DEBUG",           (anyptr) &debug,             0},
{'I', 'R', "SHOWPROGRESS",    (anyptr) &showprogress,      0},
{'S', 'V', "TOKENTRACE",      (anyptr) &tokentrace,        0},
{'S', 'V', "QUIET",           (anyptr) &quietmode,         0},
{'S', 'V', "COPYSOURCE",      (anyptr) &copysource,        0},
{'I', 'R', "MAXERRORS",	 (anyptr) &maxerrors,	      0},
{'X', ' ', "INCLUDE",         (anyptr) NULL,               2},
{'U', 'T', "LANGUAGE",        (anyptr)  language,         40},
{'S', 'V', "MODULA2",         (anyptr) &modula2,          -1},
{'S', 'T', "INTEGER16",       (anyptr) &integer16,        -1},
{'S', 'T', "DOUBLEREALS",     (anyptr) &doublereals,      -1},
{'S', 'V', "UNSIGNEDCHAR",    (anyptr) &unsignedchar,     -1},
{'S', 'V', "NEEDSIGNEDBYTE",  (anyptr) &needsignedbyte,    0},
{'S', 'V', "PASCALENUMSIZE",  (anyptr) &pascalenumsize,   -1},
{'S', 'V', "NESTEDCOMMENTS",  (anyptr) &nestedcomments,   -1},
{'S', 'V', "IMPORTALL",       (anyptr) &importall,        -1},
{'S', 'V', "IMPLMODULES",     (anyptr) &implementationmodules, -1},
{'S', 'V', "TURBOOBJECTS",    (anyptr) &turboobjects,     -1},
{'A', 'V', "EXTERNWORDS",	 (anyptr) &externwords,	      0},
{'A', 'V', "CEXTERNWORDS",	 (anyptr) &cexternwords,      0},
{'S', 'V', "PASCALSIGNIF",    (anyptr) &pascalsignif,     -1},
{'S', 'V', "PASCALCASESENS",  (anyptr) &pascalcasesens,   -1},
{'S', 'V', "DOLLARIDENTS",    (anyptr) &dollar_idents,    -1},
{'S', 'V', "IGNORENONALPHA",  (anyptr) &ignorenonalpha,   -1},
{'I', 'V', "SEEKBASE",        (anyptr) &seek_base,        -1},
{'S', 'V', "LOWPRECLOGICALS", (anyptr) &lowpreclogicals,  -1},
{'S', 'V', "COMMONEXTERN",    (anyptr) &commonextern,      0},
{'I', 'R', "INPUTTABSIZE",    (anyptr) &intabsize,         8},
{'X', 'V', "REPLACEBEFORE",   (anyptr) &replacebefore,     4},
{'S', 'T', "ANSIC",           (anyptr) &ansiC,            -1},
{'S', 'T', "C++",             (anyptr) &cplus,            -1},
{'S', 'T', "VOID*",           (anyptr) &voidstar,         -1},
{'S', 'T', "HASSIGNEDCHAR",   (anyptr) &hassignedchar,    -1},
{'S', 'V', "CASTNULL",        (anyptr) &castnull,         -1},
{'S', 'V', "COPYSTRUCTS",     (anyptr) &copystructs,      -1},
{'S', 'V', "VARIABLEARRAYS",  (anyptr) &variablearrays,   -1},
{'S', 'V', "INITPACSTRINGS",  (anyptr) &initpacstrings,   -1},
{'S', 'V', "REUSEFIELDNAMES", (anyptr) &reusefieldnames,   1},
{'S', 'V', "USEVEXTERN",      (anyptr) &usevextern,        1},
{'S', 'V', "CSIGNIF",         (anyptr) &csignif,          -1},
{'S', 'V', "USEANYPTRMACROS", (anyptr) &useAnyptrMacros,  -1},
{'S', 'V', "USEPPMACROS",     (anyptr) &usePPMacros,      -1},
{'C', 'V', "MAINTYPE",        (anyptr)  maintype,         40},
{'X', 'V', "REPLACEAFTER",    (anyptr) &replaceafter,      4},


{'U', 'T', "TARGET",          (anyptr)  target,           40},
{'S', 'T', "SIGNEDCHAR",      (anyptr) &signedchars,      -1},
{'S', 'T', "SIGNEDFIELD",     (anyptr) &signedfield,      -1},
{'S', 'T', "SIGNEDSHIFT",     (anyptr) &signedshift,      -1},
{'I', 'T', "CHARSIZE",        (anyptr) &sizeof_char,       0},
{'I', 'T', "SHORTSIZE",       (anyptr) &sizeof_short,      0},
{'I', 'T', "INTSIZE",         (anyptr) &sizeof_int,        0},
{'I', 'T', "LONGSIZE",        (anyptr) &sizeof_long,       0},
{'I', 'T', "PTRSIZE",         (anyptr) &sizeof_pointer,    0},
{'I', 'T', "DOUBLESIZE",      (anyptr) &sizeof_double,     0},
{'I', 'T', "FLOATSIZE",       (anyptr) &sizeof_float,      0},
{'I', 'T', "ENUMSIZE",        (anyptr) &sizeof_enum,       0},
{'S', 'T', "SIZE_T_LONG",     (anyptr) &size_t_long,      -1},


{'S', 'V', "NULLSTMTLINE",    (anyptr) &nullstmtline,      0},
{'S', 'V', "BRACESALWAYS",    (anyptr) &bracesalways,     -1},
{'S', 'V', "BRACELINE",       (anyptr) &braceline,        -1},
{'S', 'V', "BRACECOMBINE",    (anyptr) &bracecombine,      0},
{'S', 'V', "BRACEELSE",       (anyptr) &braceelse,         0},
{'S', 'V', "BRACEELSELINE",   (anyptr) &braceelseline,     0},
{'S', 'V', "ELSEIF",          (anyptr) &elseif,           -1},
{'S', 'V', "NEWLINEFUNCS",    (anyptr) &newlinefunctions,  0},


{'I', 'R', "PHYSTABSIZE",     (anyptr) &phystabsize,       8},
{'D', 'R', "INDENT",          (anyptr) &tabsize,           2},
{'D', 'R', "BLOCKINDENT",     (anyptr) &blockindent,       0},
{'D', 'R', "BODYINDENT",      (anyptr) &bodyindent,        0},
{'D', 'R', "FUNCARGINDENT",   (anyptr) &argindent,      1000},
{'D', 'R', "OPENBRACEINDENT", (anyptr) &openbraceindent,   0},
{'D', 'R', "CLOSEBRACEINDENT",(anyptr) &closebraceindent,  0},
{'D', 'R', "FUNCOPENINDENT",  (anyptr) &funcopenindent,    0},
{'D', 'R', "FUNCCLOSEINDENT", (anyptr) &funccloseindent,   0},
{'D', 'R', "SWITCHINDENT",    (anyptr) &switchindent,      0},
{'D', 'R', "CASEINDENT",      (anyptr) &caseindent,       -2},
{'D', 'R', "LABELINDENT",     (anyptr) &labelindent,    1000},
{'D', 'R', "STRUCTINDENT",    (anyptr) &structindent,      0},
{'D', 'R', "STRUCTINITINDENT",(anyptr) &structinitindent,  0},
{'D', 'R', "EXTRAINITINDENT", (anyptr) &extrainitindent,   2},
{'I', 'R', "EXTRAINDENT",     (anyptr) &extraindent,       2},
{'I', 'R', "BUMPINDENT",      (anyptr) &bumpindent,        1},
{'D', 'R', "CONSTINDENT",     (anyptr) &constindent,    1024},
{'D', 'R', "COMMENTINDENT",   (anyptr) &commentindent,     3},
{'D', 'R', "BRACECOMMENTINDENT",(anyptr)&bracecommentindent, 2},
{'D', 'R', "DECLCOMMENTINDENT",(anyptr)&declcommentindent, -999},
{'D', 'R', "COMMENTOVERINDENT",(anyptr)&commentoverindent, 4},  
{'I', 'R', "MINSPACING",      (anyptr) &minspacing,        2},
{'I', 'R', "MINSPACINGTHRESH",(anyptr) &minspacingthresh, -1},


{'I', 'R', "LINEWIDTH",       (anyptr) &linewidth,        78},
{'I', 'R', "MAXLINEWIDTH",    (anyptr) &maxlinewidth,     90},
{'R', 'V', "OVERWIDEPENALTY",       (anyptr) &overwidepenalty,         2500},
{'R', 'V', "OVERWIDEEXTRAPENALTY",  (anyptr) &overwideextrapenalty,     100},
{'R', 'V', "COMMABREAKPENALTY",     (anyptr) &commabreakpenalty,       1000},
{'R', 'V', "COMMABREAKEXTRAPENALTY",(anyptr) &commabreakextrapenalty,   500},
{'R', 'V', "ASSIGNBREAKPENALTY",    (anyptr) &assignbreakpenalty,      5000},
{'R', 'V', "ASSIGNBREAKEXTRAPENALTY",(anyptr)&assignbreakextrapenalty, 3000},
{'R', 'V', "SPECIALARGBREAKPENALTY",(anyptr) &specialargbreakpenalty,   500},
{'R', 'V', "OPBREAKPENALTY",        (anyptr) &opbreakpenalty,          2500},
{'R', 'V', "OPBREAKEXTRAPENALTY",   (anyptr) &opbreakextrapenalty,     2000},
{'R', 'V', "LOGBREAKPENALTY",       (anyptr) &logbreakpenalty,          500},
{'R', 'V', "LOGBREAKEXTRAPENALTY",  (anyptr) &logbreakextrapenalty,     100},
{'R', 'V', "RELBREAKPENALTY",       (anyptr) &relbreakpenalty,         2000},
{'R', 'V', "RELBREAKEXTRAPENALTY",  (anyptr) &relbreakextrapenalty,    1000},
{'R', 'V', "EXHYPHENPENALTY",       (anyptr) &exhyphenpenalty,         1000},
{'R', 'V', "MOREBREAKPENALTY",      (anyptr) &morebreakpenalty,        -500},
{'R', 'V', "MOREBREAKEXTRAPENALTY", (anyptr) &morebreakextrapenalty,   -300},
{'R', 'V', "QMARKBREAKPENALTY",     (anyptr) &qmarkbreakpenalty,       5000},
{'R', 'V', "QMARKBREAKEXTRAPENALTY",(anyptr) &qmarkbreakextrapenalty,  3000},
{'R', 'V', "PARENBREAKPENALTY",     (anyptr) &parenbreakpenalty,       2500},
{'R', 'V', "PARENBREAKEXTRAPENALTY",(anyptr) &parenbreakextrapenalty,  1000},
{'R', 'V', "WRONGSIDEPENALTY",      (anyptr) &wrongsidepenalty,        1000},
{'R', 'V', "EARLYBREAKPENALTY",     (anyptr) &earlybreakpenalty,        100},
{'R', 'V', "EXTRAINDENTPENALTY",    (anyptr) &extraindentpenalty,      3000},
{'R', 'V', "BUMPINDENTPENALTY",     (anyptr) &bumpindentpenalty,       1000},
{'R', 'V', "NOBUMPINDENTPENALTY",   (anyptr) &nobumpindentpenalty,     2500},
{'R', 'V', "INDENTAMOUNTPENALTY",   (anyptr) &indentamountpenalty,       50},
{'R', 'V', "SAMEINDENTPENALTY",     (anyptr) &sameindentpenalty,        500},
{'R', 'V', "SHOWBADLIMIT",          (anyptr) &showbadlimit,            -120},
{'L', 'R', "MAXLINEBREAKTRIES", (anyptr) &maxalts,      5000},
{'G', 'V', "ALLORNONEBREAK",  (anyptr)  NULL,             FALLBREAK},
{'G', 'V', "ONESPECIALARG",   (anyptr)  NULL,             FSPCARG1},
{'G', 'V', "TWOSPECIALARGS",  (anyptr)  NULL,             FSPCARG2},
{'G', 'V', "THREESPECIALARGS",(anyptr)  NULL,             FSPCARG3},
{'B', 'V', "BREAKARITH",      (anyptr) &breakbeforearith,  BRK_RIGHT},
{'B', 'V', "BREAKREL",        (anyptr) &breakbeforerel,    BRK_RIGHT},
{'B', 'V', "BREAKLOG",        (anyptr) &breakbeforelog,    BRK_RIGHT},
{'B', 'V', "BREAKDOT",        (anyptr) &breakbeforedot,    BRK_RIGHT},
{'B', 'V', "BREAKASSIGN",     (anyptr) &breakbeforeassign, BRK_RIGHT},
{'S', 'V', "FOR_ALLORNONE",   (anyptr) &for_allornone,     1},


{'S', 'V', "NOBANNER",        (anyptr) &nobanner,	      0},
{'S', 'V', "SLASHSLASH",      (anyptr) &slashslash,       -1},
{'S', 'V', "EATCOMMENTS",     (anyptr) &eatcomments,       0},
{'S', 'V', "SPITCOMMENTS",    (anyptr) &spitcomments,      0},
{'S', 'V', "SPITORPHANCOMMENTS",(anyptr)&spitorphancomments, 0},
{'S', 'V', "COMMENTAFTER",    (anyptr) &commentafter,     -1},
{'S', 'V', "BLANKAFTER",      (anyptr) &blankafter,        1},
{'A', 'V', "EATNOTES",        (anyptr) &eatnotes,          0},


{'C', 'V', "FIXEDCOMMENT",    (anyptr)  fixedcomment,     40},
{'C', 'V', "PERMANENTCOMMENT",(anyptr)  permanentcomment, 40},
{'C', 'V', "INTERFACECOMMENT",(anyptr)  interfacecomment, 40},
{'C', 'V', "EMBEDCOMMENT",    (anyptr)  embedcomment,     40},
{'C', 'V', "SKIPCOMMENT",     (anyptr)  skipcomment,      40},
{'C', 'V', "NOSKIPCOMMENT",   (anyptr)  noskipcomment,    40},
{'C', 'V', "SIGNEDCOMMENT",   (anyptr)  signedcomment,    40},
{'C', 'V', "UNSIGNEDCOMMENT", (anyptr)  unsignedcomment,  40},
{'C', 'V', "TAGCOMMENT",      (anyptr)  tagcomment,       40},


{'I', 'V', "MAJORSPACING",    (anyptr) &majorspace,        2},
{'I', 'V', "MINORSPACING",    (anyptr) &minorspace,        1},
{'I', 'V', "DECLSPACING",     (anyptr) &declspace,        -1},
{'I', 'V', "FUNCSPACING",     (anyptr) &functionspace,     2},
{'I', 'V', "MINFUNCSPACING",  (anyptr) &minfuncspace,      1},
{'S', 'V', "EXTRAPARENS",     (anyptr) &extraparens,      -1},
{'S', 'V', "BREAKADDPARENS",  (anyptr) &breakparens,      -1},
{'S', 'V', "RETURNPARENS",    (anyptr) &returnparens,     -1},
{'S', 'V', "SPACEEXPRS",      (anyptr) &spaceexprs,       -1},
{'S', 'V', "SPACEFUNCS",	 (anyptr) &spacefuncs,	      0},
{'S', 'V', "SPACECOMMAS",	 (anyptr) &spacecommas,	      1},
{'S', 'V', "IMPLICITZERO",    (anyptr) &implicitzero,     -1},
{'S', 'V', "STARINDEX",       (anyptr) &starindex,        -1},
{'S', 'V', "ADDINDEX",        (anyptr) &addindex,         -1},
{'S', 'V', "STARARRAYS",      (anyptr) &stararrays,        1},
{'S', 'V', "STARFUNCTIONS",   (anyptr) &starfunctions,    -1},
{'S', 'V', "SPACESTARS",      (anyptr) &spacestars,        0},
{'S', 'V', "CALLCASTS",       (anyptr) &callcasts,        -1},
{'S', 'V', "POSTINCREMENT",   (anyptr) &postincrement,     1},
{'S', 'V', "MIXVARS",         (anyptr) &mixvars,          -1},
{'S', 'V', "MIXTYPES",        (anyptr) &mixtypes,         -1},
{'S', 'V', "MIXFIELDS",       (anyptr) &mixfields,        -1},
{'S', 'V', "MIXINITS",        (anyptr) &mixinits,         -1},
{'S', 'V', "MAINLOCALS",      (anyptr) &mainlocals,        1},
{'S', 'V', "NULLCHAR",        (anyptr) &nullcharconst,     1},
{'S', 'V', "HIGHCHARINT",     (anyptr) &highcharints,      1},
{'S', 'V', "ANONYMOUSUNIONS", (anyptr) &anonymousunions,  -1},
{'I', 'V', "CASESPACING",     (anyptr) &casespacing,       1},
{'D', 'V', "CASETABS",        (anyptr) &casetabs,       1000},
{'I', 'V', "CASELIMIT",       (anyptr) &caselimit,         9},
{'S', 'V', "USECOMMAS",       (anyptr) &usecommas,        -1},
{'S', 'V', "USERETURNS",      (anyptr) &usereturns,        1},
{'I', 'V', "RETURNLIMIT",     (anyptr) &returnlimit,       3},
{'S', 'V', "USEBREAKS",       (anyptr) &usebreaks,         1},
{'I', 'V', "BREAKLIMIT",      (anyptr) &breaklimit,        2},
{'I', 'V', "CONTINUELIMIT",   (anyptr) &continuelimit,     5},
{'S', 'V', "INFLOOPSTYLE",    (anyptr) &infloopstyle,      0},


{'C', 'V', "CODEFILENAME",    (anyptr)  codefnfmt,        40},
{'C', 'V', "MODULEFILENAME",  (anyptr)  modulefnfmt,      40},
{'C', 'V', "HEADERFILENAME",  (anyptr)  headerfnfmt,      40},
{'C', 'V', "HEADERFILENAME2", (anyptr)  headerfnfmt2,     40},
{'C', 'V', "SELFINCLUDENAME", (anyptr)  selfincludefmt,   40},
{'C', 'V', "LOGFILENAME",     (anyptr)  logfnfmt,         40},
{'C', 'V', "INCLUDEFILENAME", (anyptr)  includefnfmt,     40},
{'C', 'V', "INCLUDEOUTFILENAME", (anyptr) includeoutfnfmt, 40},
{'S', 'V', "SYMCASE",         (anyptr) &symcase,          -1},
{'C', 'V', "SYMBOLFORMAT",    (anyptr)  symbolformat,     40},
{'C', 'V', "CONSTFORMAT",     (anyptr)  constformat,      40},
{'C', 'V', "MODULEFORMAT",    (anyptr)  moduleformat,     40},
{'C', 'V', "FUNCTIONFORMAT",  (anyptr)  functionformat,   40},
{'C', 'V', "VARFORMAT",       (anyptr)  varformat,        40},
{'C', 'V', "FIELDFORMAT",     (anyptr)  fieldformat,      40},
{'C', 'V', "TYPEFORMAT",      (anyptr)  typeformat,       40},
{'C', 'V', "ENUMFORMAT",      (anyptr)  enumformat,       40},
{'C', 'V', "RETURNVALUENAME", (anyptr)  name_RETV,        40},
{'C', 'V', "UNITINITNAME",    (anyptr)  name_UNITINIT,    40},
{'C', 'V', "HSYMBOLNAME",     (anyptr)  name_HSYMBOL,     40},
{'C', 'V', "GSYMBOLNAME",     (anyptr)  name_GSYMBOL,     40},
{'C', 'V', "STRINGMAXNAME",   (anyptr)  name_STRMAX,      40},
{'C', 'V', "ARRAYMINNAME",    (anyptr)  name_ALOW,        40},
{'C', 'V', "ARRAYMAXNAME",    (anyptr)  name_AHIGH,       40},
{'C', 'V', "COPYPARNAME",     (anyptr)  name_COPYPAR,     40},
{'C', 'V', "STATICLINKNAME",  (anyptr)  name_LINK,        40},
{'C', 'V', "LOCALVARSSTRUCT", (anyptr)  name_LOC,         40},
{'C', 'V', "LOCALVARSNAME",   (anyptr)  name_VARS,        40},
{'C', 'V', "FWDSTRUCTNAME",   (anyptr)  name_STRUCT,      40},
{'C', 'V', "ENUMLISTNAME",    (anyptr)  name_ENUM,        40},
{'C', 'V', "UNIONNAME",       (anyptr)  name_UNION,       40},
{'C', 'V', "UNIONPARTNAME",   (anyptr)  name_VARIANT,     40},
{'C', 'V', "FAKESTRUCTNAME",  (anyptr)  name_FAKESTRUCT,  40},
{'S', 'V', "TAGSTRUCTS",      (anyptr) &tagstructs,        0},
{'C', 'V', "LABELNAME",       (anyptr)  name_LABEL,       40},
{'C', 'V', "LABELVARNAME",    (anyptr)  name_LABVAR,      40},
{'C', 'V', "TEMPNAME",        (anyptr)  name_TEMP,        40},
{'C', 'V', "DUMMYNAME",       (anyptr)  name_DUMMY,       40},
{'C', 'V', "FORNAME",         (anyptr)  name_FOR,         40},
{'C', 'V', "WITHNAME",        (anyptr)  name_WITH,        40},
{'C', 'V', "PTRNAME",         (anyptr)  name_PTR,         40},
{'C', 'V', "STRINGNAME",      (anyptr)  name_STRING,      40},
{'C', 'V', "SETNAME",         (anyptr)  name_SET,         40},
{'C', 'V', "FNVARNAME",       (anyptr)  name_FNVAR,       40},
{'C', 'V', "FNSIZENAME",      (anyptr)  name_FNSIZE,      40},
{'C', 'V', "ALTERNATENAME1",  (anyptr)  alternatename1,   40},
{'C', 'V', "ALTERNATENAME2",  (anyptr)  alternatename2,   40},
{'C', 'V', "ALTERNATENAME",   (anyptr)  alternatename,    40},
{'C', 'V', "EXPORTSYMBOL",    (anyptr)  exportsymbol,     40},
{'C', 'V', "EXPORT_SYMBOL",   (anyptr)  export_symbol,    40},
{'C', 'V', "ALIAS",           (anyptr)  externalias,      40},
{'X', 'V', "SYNONYM",         (anyptr)  NULL,              3},
{'X', 'V', "NAMEOF",          (anyptr) &nameoflist,        1},
{'G', 'V', "AVOIDNAME",       (anyptr)  NULL,             AVOIDNAME},
{'G', 'V', "AVOIDGLOBALNAME", (anyptr)  NULL,             AVOIDGLOB},
{'G', 'V', "WARNNAME",        (anyptr)  NULL,             WARNNAME},
{'G', 'V', "NOSIDEEFFECTS",   (anyptr)  NULL,             NOSIDEEFF},
{'G', 'V', "STRUCTFUNCTION",  (anyptr)  NULL,             STRUCTF},
{'G', 'V', "STRLAPFUNCTION",  (anyptr)  NULL,             STRLAPF},
{'F', 'V', "LEAVEALONE",      (anyptr)  NULL,             LEAVEALONE},
{'G', 'V', "DETERMINISTIC",   (anyptr)  NULL,             DETERMF},
{'G', 'V', "NEEDSTATIC",      (anyptr)  NULL,             NEEDSTATIC},
{'S', 'V', "WARNNAMES",       (anyptr) &warnnames,         0},
{'M', 'V', "VARMACRO",        (anyptr)  NULL,             MAC_VAR},
{'M', 'V', "CONSTMACRO",      (anyptr)  NULL,             MAC_CONST},
{'M', 'V', "FIELDMACRO",      (anyptr)  NULL,             MAC_FIELD},
{'M', 'V', "FUNCMACRO",       (anyptr)  NULL,             MAC_FUNC},
{'S', 'V', "WARNMACROS",      (anyptr) &warnmacros,        0},


{'A', 'V', "INITIALCALLS",    (anyptr) &initialcalls,      0},
{'S', 'V', "EXPANDINCLUDES",  (anyptr) &expandincludes,   -1},
{'S', 'V', "COLLECTNEST",     (anyptr) &collectnest,       1},
{'S', 'V', "SHORTCIRCUIT",    (anyptr) &shortcircuit,     -1},
{'S', 'V', "SHORTOPT",        (anyptr) &shortopt,          1},
{'S', 'V', "ELIMDEADCODE",    (anyptr) &elimdeadcode,      1},
{'S', 'V', "ANALYZEFLOW",     (anyptr) &analyzeflow,       1},
{'S', 'V', "FOLDCONSTANTS",   (anyptr) &foldconsts,       -1},
{'S', 'V', "FOLDSTRCONSTANTS",(anyptr) &foldstrconsts,    -1},
{'S', 'V', "CHARCONSTS",	 (anyptr) &charconsts,        1},
{'S', 'V', "USECONSTS",       (anyptr) &useconsts,        -1},
{'S', 'V', "USEUNDEF",        (anyptr) &useundef,          1},
{'S', 'V', "USEINITS",        (anyptr) &useinits,         -1},
{'L', 'V', "SKIPINDICES",     (anyptr) &skipindices,       0},
{'S', 'V', "OFFSETFORLOOPS",  (anyptr) &offsetforloops,    1},
{'S', 'V', "FOREVALORDER",    (anyptr) &forevalorder,      0},
{'S', 'V', "STRINGLEADERS",   (anyptr) &stringleaders,     2},
{'S', 'V', "STOREFILENAMES",  (anyptr) &storefilenames,   -1},
{'S', 'V', "CHARFILETEXT",    (anyptr) &charfiletext,     -1},
{'S', 'V', "SQUEEZESUBR",     (anyptr) &squeezesubr,       1},
{'S', 'T', "USEENUM",         (anyptr) &useenum,          -1},
{'S', 'V', "SQUEEZEENUM",     (anyptr) &enumbyte,         -1},
{'S', 'V', "COMPENUMS",       (anyptr) &compenums,        -1},
{'S', 'V', "PRESERVETYPES",   (anyptr) &preservetypes,     1},
{'S', 'V', "PRESERVEPOINTERS",(anyptr) &preservepointers,  0},
{'S', 'V', "PRESERVESTRINGS", (anyptr) &preservestrings,  -1},
{'S', 'V', "PACKING",         (anyptr) &packing,           1},
{'S', 'V', "PACKSIGNED",      (anyptr) &packsigned,        1},
{'I', 'V', "STRINGCEILING",   (anyptr) &stringceiling,   255},
{'I', 'V', "STRINGDEFAULT",   (anyptr) &stringdefault,   255},
{'I', 'V', "STRINGTRUNCLIMIT",(anyptr) &stringtrunclimit, -1},
{'I', 'V', "LONGSTRINGSIZE",  (anyptr) &longstringsize,   -1},
{'S', 'V', "KEEPNULLS",       (anyptr) &keepnulls,         0},
{'S', 'V', "HIGHCHARBITS",    (anyptr) &highcharbits,     -1},
{'S', 'V', "ALWAYSCOPYVALUES",(anyptr) &alwayscopyvalues,  0},
{'S', 'V', "STATICFUNCTIONS", (anyptr) &use_static,        1},
{'S', 'V', "STATICVARIABLES", (anyptr) &var_static,        1},
{'S', 'V', "VOIDARGS",        (anyptr) &void_args,        -1},
{'S', 'V', "PROTOTYPES",      (anyptr) &prototypes,       -1},
{'S', 'V', "FULLPROTOTYPING", (anyptr) &fullprototyping,  -1},
{'S', 'V', "PROCPTRPROTOTYPES",(anyptr)&procptrprototypes, 1},
{'S', 'V', "CASTARGS",        (anyptr) &castargs,         -1},
{'S', 'V', "CASTLONGARGS",    (anyptr) &castlongargs,     -1},
{'S', 'V', "PROMOTEARGS",     (anyptr) &promoteargs,      -1},
{'S', 'V', "FIXPROMOTEDARGS", (anyptr) &fixpromotedargs,   1},
{'S', 'V', "PROMOTEENUMS",    (anyptr) &promote_enums,    -1},
{'S', 'V', "STATICLINKS",     (anyptr) &hasstaticlinks,   -1},
{'S', 'V', "VARSTRINGS",      (anyptr) &varstrings,        0},
{'S', 'V', "VARFILES",        (anyptr) &varfiles,          1},
{'S', 'V', "USEREFS",         (anyptr) &userefs,          -1},
{'S', 'V', "ADDRSTDFILES",    (anyptr) &addrstdfiles,      0},
{'S', 'V', "COPYSTRUCTFUNCS", (anyptr) &copystructfuncs,  -1},
{'S', 'V', "ATAN2",           (anyptr) &atan2flag,         0},
{'S', 'V', "BITWISEMOD",      (anyptr) &mod_po2,          -1},
{'S', 'V', "BITWISEDIV",      (anyptr) &div_po2,          -1},
{'S', 'V', "ASSUMEBITS",      (anyptr) &assumebits,        0},
{'S', 'V', "ASSUMESIGNS",     (anyptr) &assumesigns,       1},
{'S', 'V', "NEWDELETE",       (anyptr) &newdelete,        -1},
{'S', 'V', "ALLOCZERONIL",    (anyptr) &alloczeronil,      0},
{'S', 'V', "PRINTFONLY",      (anyptr) &printfonly,       -1},
{'S', 'V', "MIXWRITELNS",     (anyptr) &mixwritelns,       1},
{'S', 'V', "MESSAGESTDERR",   (anyptr) &messagestderr,     1},
{'I', 'V', "INTEGERWIDTH",    (anyptr) &integerwidth,     -1},
{'I', 'V', "REALWIDTH",       (anyptr) &realwidth,        12},
{'S', 'V', "FORMATSTRINGS",   (anyptr) &formatstrings,     0},
{'S', 'V', "WHILEFGETS",      (anyptr) &whilefgets,        1},
{'S', 'V', "USEGETS",         (anyptr) &usegets,           1},
{'C', 'V', "FLOATSCANFCODE",  (anyptr)  floatscanfcode,   40},
{'S', 'V', "NEWLINESPACE",    (anyptr) &newlinespace,     -1},
{'S', 'V', "BUILDREADS",      (anyptr) &buildreads,        1},
{'S', 'V', "BUILDWRITES",     (anyptr) &buildwrites,       1},
{'S', 'V', "BINARYMODE",      (anyptr) &binarymode,        1},
{'S', 'V', "READWRITEOPEN",   (anyptr) &readwriteopen,    -1},
{'C', 'V', "OPENMODE",        (anyptr)  openmode,         40},
{'S', 'V', "LITERALFILES",    (anyptr) &literalfilesflag, -1},
{'A', 'V', "LITERALFILE",     (anyptr) &literalfiles,      0},
{'S', 'V', "STRUCTFILES",     (anyptr) &structfilesflag,   0},
{'A', 'V', "STRUCTFILE",      (anyptr) &structfiles,       0},
{'C', 'V', "FILENAMEFILTER",  (anyptr)  filenamefilter,   40},
{'S', 'V', "FULLSTRWRITE",    (anyptr) &fullstrwrite,     -1},
{'S', 'V', "FULLSTRREAD",     (anyptr) &fullstrread,       1},
{'I', 'R', "SETBITS",         (anyptr) &setbits,          -1},
{'I', 'V', "DEFAULTSETSIZE",  (anyptr) &defaultsetsize,   -1},
{'S', 'V', "SMALLSETCONST",   (anyptr) &smallsetconst,    -2},
{'S', 'V', "BIGSETCONST",     (anyptr) &bigsetconst,       1},
{'S', 'V', "LELERANGE",       (anyptr) &lelerange,         0},
{'S', 'V', "UNSIGNEDTRICK",   (anyptr) &unsignedtrick,     1},
{'S', 'V', "USEISALPHA",      (anyptr) &useisalpha,        1},
{'S', 'V', "USEISSPACE",      (anyptr) &useisspace,        0},
{'S', 'V', "USESTRNCMP",	 (anyptr) &usestrncmp,	      1},


{'G', 'V', "WARNLIBRARY",     (anyptr)  NULL,             WARNLIBR},
{'S', 'V', "QUOTEINCLUDES",   (anyptr) &quoteincludes,     1},
{'X', 'V', "IMPORTFROM",      (anyptr) &importfrom,        1},
{'A', 'V', "IMPORTDIR",       (anyptr) &importdirs,        0},
{'A', 'V', "INCLUDEDIR",      (anyptr) &includedirs,       0},
{'X', 'V', "INCLUDEFROM",     (anyptr) &includefrom,       1},
{'A', 'V', "LIBRARYFILE",     (anyptr) &librfiles,         0},
{'X', 'V', "SHELLVARS",       (anyptr) &shellvars,         1},
{'C', 'V', "HEADERNAME",      (anyptr)  p2c_h_name,       40},
{'C', 'V', "PROCTYPENAME",    (anyptr)  name_PROCEDURE,   40},
{'C', 'V', "UCHARNAME",       (anyptr)  name_UCHAR,       40},
{'C', 'V', "SCHARNAME",       (anyptr)  name_SCHAR,       40},
{'C', 'V', "BOOLEANNAME",     (anyptr)  name_BOOLEAN,     40},
{'C', 'V', "TRUENAME",        (anyptr)  name_TRUE,        40},
{'C', 'V', "FALSENAME",       (anyptr)  name_FALSE,       40},
{'C', 'V', "NULLNAME",        (anyptr)  name_NULL,        40},
{'C', 'V', "ESCAPECODENAME",  (anyptr)  name_ESCAPECODE,  40},
{'C', 'V', "IORESULTNAME",    (anyptr)  name_IORESULT,    40},
{'C', 'V', "ARGCNAME",        (anyptr)  name_ARGC,        40},
{'C', 'V', "ARGVNAME",        (anyptr)  name_ARGV,        40},
{'C', 'V', "MAINNAME",        (anyptr)  name_MAIN,        40},
{'C', 'V', "ESCAPENAME",      (anyptr)  name_ESCAPE,      40},
{'C', 'V', "ESCIONAME",       (anyptr)  name_ESCIO,       40},
{'C', 'V', "ESCIO2NAME",      (anyptr)  name_ESCIO2,      40},
{'C', 'V', "CHECKIONAME",     (anyptr)  name_CHKIO,       40},
{'C', 'V', "SETIONAME",       (anyptr)  name_SETIO,       40},
{'C', 'V', "FILENOTFOUNDNAME",(anyptr)  filenotfoundname, 40},
{'C', 'V', "FILENOTOPENNAME", (anyptr)  filenotopenname,  40},
{'C', 'V', "FILEWRITEERRORNAME",(anyptr)filewriteerrorname,40},
{'C', 'V', "BADINPUTFORMATNAME",(anyptr)badinputformatname,40},
{'C', 'V', "ENDOFFILENAME",   (anyptr)  endoffilename,    40},
{'C', 'V', "OUTMEMNAME",      (anyptr)  name_OUTMEM,      40},
{'C', 'V', "CASECHECKNAME",   (anyptr)  name_CASECHECK,   40},
{'C', 'V', "NILCHECKNAME",    (anyptr)  name_NILCHECK,    40},
{'C', 'V', "SETBITSNAME",     (anyptr)  name_SETBITS,     40},
{'S', 'V', "SPRINTFVALUE",    (anyptr) &sprintf_value,    -1},
{'C', 'V', "SPRINTFNAME",     (anyptr)  sprintfname,      40},
{'C', 'V', "MEMCPYNAME",      (anyptr)  memcpyname,       40},
{'C', 'V', "ROUNDNAME",       (anyptr)  roundname,        40},
{'C', 'V', "DIVNAME",	 (anyptr)  divname,	     40},
{'C', 'V', "MODNAME",	 (anyptr)  modname,	     40},
{'C', 'V', "REMNAME",	 (anyptr)  remname,	     40},
{'C', 'V', "STRCICMPNAME",    (anyptr)  strcicmpname,     40},
{'C', 'V', "STRSUBNAME",      (anyptr)  strsubname,       40},
{'C', 'V', "STRPOSNAME",      (anyptr)  strposname,       40},
{'S', 'V', "STRCPYLEFT",      (anyptr) &strcpyleft,        1},
{'C', 'V', "STRDELETENAME",   (anyptr)  strdeletename,    40},
{'C', 'V', "STRINSERTNAME",   (anyptr)  strinsertname,    40},
{'C', 'V', "STRMOVENAME",     (anyptr)  strmovename,	     40},
{'C', 'V', "STRLTRIMNAME",    (anyptr)  strltrimname,     40},
{'C', 'V', "STRRTRIMNAME",    (anyptr)  strrtrimname,     40},
{'C', 'V', "STRRPTNAME",      (anyptr)  strrptname,       40},
{'C', 'V', "STRPADNAME",      (anyptr)  strpadname,       40},
{'C', 'V', "OFSNAME",         (anyptr)  OFSname,          40},
{'C', 'V', "SEGNAME",         (anyptr)  SEGname,          40},
{'C', 'V', "ABSNAME",         (anyptr)  absname,          40},
{'C', 'V', "ODDNAME",         (anyptr)  oddname,          40},
{'C', 'V', "EVENNAME",        (anyptr)  evenname,         40},
{'C', 'V', "SWAPNAME",        (anyptr)  swapname,         40},
{'C', 'V', "MALLOCNAME",      (anyptr)  mallocname,       40},
{'C', 'V', "FREENAME",        (anyptr)  freename,         40},
{'C', 'V', "FREERVALUENAME",  (anyptr)  freervaluename,   40},
{'X', 'V', "SPECIALMALLOC",   (anyptr) &specialmallocs,    1},
{'X', 'V', "SPECIALFREE",     (anyptr) &specialfrees,      1},
{'X', 'V', "SPECIALSIZEOF",   (anyptr) &specialsizeofs,    1},
{'C', 'V', "RANDREALNAME",    (anyptr)  randrealname,     40},
{'C', 'V', "RANDINTNAME",     (anyptr)  randintname,      40},
{'C', 'V', "RANDOMIZENAME",   (anyptr)  randomizename,    40},
{'C', 'V', "SKIPSPACENAME",   (anyptr)  skipspacename,    40},
{'C', 'V', "SKIPNLSPACENAME", (anyptr)  skipnlspacename,  40},
{'C', 'V', "READLNNAME",      (anyptr)  readlnname,       40},
{'C', 'V', "FREOPENNAME",     (anyptr)  freopenname,      40},
{'C', 'V', "EOFNAME",         (anyptr)  eofname,          40},
{'C', 'V', "EOLNNAME",        (anyptr)  eolnname,         40},
{'C', 'V', "FILEPOSNAME",     (anyptr)  fileposname,      40},
{'C', 'V', "MAXPOSNAME",      (anyptr)  maxposname,       40},
{'C', 'V', "SETUNIONNAME",    (anyptr)  setunionname,     40},
{'C', 'V', "SETINTNAME",      (anyptr)  setintname,       40},
{'C', 'V', "SETDIFFNAME",     (anyptr)  setdiffname,      40},
{'C', 'V', "SETXORNAME",      (anyptr)  setxorname,       40},
{'C', 'V', "SETINNAME",       (anyptr)  setinname,        40},
{'C', 'V', "SETADDNAME",      (anyptr)  setaddname,       40},
{'C', 'V', "SETADDRANGENAME", (anyptr)  setaddrangename,  40},
{'C', 'V', "SETREMNAME",      (anyptr)  setremname,       40},
{'C', 'V', "SETEQUALNAME",    (anyptr)  setequalname,     40},
{'C', 'V', "SUBSETNAME",      (anyptr)  subsetname,       40},
{'C', 'V', "SETCOPYNAME",     (anyptr)  setcopyname,      40},
{'C', 'V', "SETEXPANDNAME",   (anyptr)  setexpandname,    40},
{'C', 'V', "SETPACKNAME",     (anyptr)  setpackname,      40},
{'C', 'V', "SIGNEXTENDNAME",  (anyptr)  signextname,      40},
{'C', 'V', "GETBITSNAME",     (anyptr)  getbitsname,      40},
{'C', 'V', "CLRBITSNAME",     (anyptr)  clrbitsname,      40},
{'C', 'V', "PUTBITSNAME",     (anyptr)  putbitsname,      40},
{'C', 'V', "STOREBITSNAME",   (anyptr)  storebitsname,    40},
{'C', 'V', "DECLBUFNAME",	 (anyptr)  declbufname,	     40},
{'C', 'V', "DECLBUFNCNAME",	 (anyptr)  declbufncname,    40},
{'A', 'V', "BUFFEREDFILE",    (anyptr) &bufferedfiles,     0},
{'A', 'V', "UNBUFFEREDFILE",  (anyptr) &unbufferedfiles,   0},
{'C', 'V', "RESETBUFNAME",	 (anyptr)  resetbufname,     40},
{'C', 'V', "SETUPBUFNAME",	 (anyptr)  setupbufname,     40},
{'C', 'V', "GETFBUFNAME",     (anyptr)  getfbufname,      40},
{'C', 'V', "CHARGETFBUFNAME", (anyptr)  chargetfbufname,  40},
{'C', 'V', "ARRAYGETFBUFNAME",(anyptr)  arraygetfbufname, 40},
{'C', 'V', "PUTFBUFNAME",     (anyptr)  putfbufname,      40},
{'C', 'V', "CHARPUTFBUFNAME", (anyptr)  charputfbufname,  40},
{'C', 'V', "ARRAYPUTFBUFNAME",(anyptr)  arrayputfbufname, 40},
{'C', 'V', "GETNAME",         (anyptr)  getname,          40},
{'C', 'V', "CHARGETNAME",     (anyptr)  chargetname,      40},
{'C', 'V', "ARRAYGETNAME",    (anyptr)  arraygetname,     40},
{'C', 'V', "PUTNAME",         (anyptr)  putname,          40},
{'C', 'V', "CHARPUTNAME",     (anyptr)  charputname,      40},
{'C', 'V', "ARRAYPUTNAME",    (anyptr)  arrayputname,     40},
{'C', 'V', "EOFBUFNAME",      (anyptr)  eofbufname,       40},
{'C', 'V', "FILEPOSBUFNAME",  (anyptr)  fileposbufname,   40},


{'S', 'V', "CASECHECK",       (anyptr) &casecheck,         0},
{'S', 'V', "ARRAYCHECK",      (anyptr) &arraycheck,        0},
{'S', 'V', "RANGECHECK",      (anyptr) &rangecheck,        0},
{'S', 'V', "NILCHECK",        (anyptr) &nilcheck,          0},
{'S', 'V', "MALLOCCHECK",     (anyptr) &malloccheck,       0},
{'S', 'V', "CHECKFILEOPEN",   (anyptr) &checkfileopen,     1},
{'S', 'V', "CHECKFILEISOPEN", (anyptr) &checkfileisopen,   0},
{'S', 'V', "CHECKFILEWRITE",  (anyptr) &checkfilewrite,    2},
{'S', 'V', "CHECKREADFORMAT", (anyptr) &checkreadformat,   2},
{'S', 'V', "CHECKFILEEOF",    (anyptr) &checkfileeof,      2},
{'S', 'V', "CHECKSTDINEOF",   (anyptr) &checkstdineof,     2},
{'S', 'V', "CHECKFILESEEK",   (anyptr) &checkfileseek,     2},
]
__eof__

data = data.gsub(/\{/, "[").gsub(/\}/, "]").gsub(/\(\w+\)/, "").gsub(/\bNULL\b/, "nil").gsub(/\&(\w+)/, 'func(\1)')
puts data


